name: FirstPlugin
main: me.EnderVizion.FirstPlugin.FirstPlugin
version: 1.0.3b
commands:
   website:
      description: Display the website link.
      usage: /<command>
   stafflist:
      description: Display the list of staff.
      usage: /<command>
   helpme:
      description: Self Explanatory 
      usage: /<command>
   rateserver:
      description: Rate the server in one word and maybe get some diamonds!
      usage: /<command> <comment>
   dropcountdown:
      description: Start the Drop Party countdown!
      usage: /<command>